create table if not exists public.pnrs (
    id bigint generated by default as identity primary key,
    pnr_number varchar(10) not null,
    email text not null,
    train_number text,
    train_name text,
    journey_date date,
    previous_status text,
    current_status text,
    last_checked_at timestamptz,
    from_station_name text,
    from_station_code text,
    to_station_name text,
    to_station_code text,
    chart_prepared boolean not null default false,
    monitor_stop_reason text,
    monitor_stopped_at timestamptz,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create unique index if not exists unique_active_pnr
on public.pnrs (pnr_number)
where active = true;

create table if not exists public.status_history (
    id bigint generated by default as identity primary key,
    pnr_id bigint not null references public.pnrs(id) on delete cascade,
    old_status text,
    new_status text not null,
    checked_at timestamptz not null default now()
);

create index if not exists idx_pnrs_active
on public.pnrs(active);

create index if not exists idx_status_history_pnr
on public.status_history(pnr_id);

-- The backend uses the Supabase service-role key, so RLS can remain enabled.
alter table public.pnrs enable row level security;
alter table public.status_history enable row level security;
